---
title: "What time should I leave?"
author: "A PUBH 7462 student"
format: 
  html:
    embed-resources: true
editor: visual
---

```{r include=FALSE}
#| echo: false
#| message: false
#| warning: false


## Load the API key
api_key <- Sys.getenv("MAPS_API_KEY")

```

```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(paletteer)
library(plotly)
library(leaflet)
library(osmdata)
library(ggmap)
library(tidycensus)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

```

```{r echo=FALSE}
#From OSM
hennepin.box <- osmdata::getbb("hennepin")

#Get the base map (foundational layer)
hennepin.base.map <- get_map(
                       location = hennepin.box,
                       source   = "stamen",
                       maptype  = "watercolor",
                       crop = TRUE
                      )

api_key <- Sys.getenv("MAPS_API_KEY")

census_api_key(api_key, overwrite = TRUE)


#Call the ACS API, returns a sf object
hennepin_pop.df <- get_acs(
  geography = "tract",
  variables = "B01002_001E", 
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE,
  cb        = FALSE
)

#Plot normally
income.gg <- ggplot() + 
  geom_sf(data = hennepin_pop.df, aes(fill = estimate)) + 
  labs(title = "Hennepin County 2020 Median Age") + 
  theme_void() + 
  scale_fill_viridis_c("Median Age")

#Display
income.gg
```
